name: Build docs website

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install uv - latest if not defined in `pyproject.toml`
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.14"

      - name: Generate HTML docs with pdoc
        run: uv run pdoc arma3_offline_map_lib -o docs
      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs/

  # Deploy artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
